import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import RecoilContextProvider from "@/lib/RecoilContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body className="pl-32 pr-32">
     <RecoilContextProvider>
      <Navbar/>
        {children}
      </RecoilContextProvider>
        </body>       
    </html>
  );
}
